apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name:  e2e-task
spec:
  inputs:
    resources:
      - name: source-repo
        type: git

  steps:
    - name: build
      image: golang
      workingDir: /workspace/source-repo
      command:
        - make
      args:
        - build
    - name: e2e-test
      image: golang
      workingDir: /workspace/source-repo
      command:
        - make
      args:
        - e2e
      securityContext:
        privileged: true
